# Generated by Django 4.2.17 on 2025-01-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_genres_alter_movie_options_and_more'),
        ('forum', '0004_forumpost_approved_post_forumpost_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='forum_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forumpost'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
