# Generated by Django 4.2.17 on 2025-01-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_postcomment_post_postcomment_forum_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='forum_post',
            field=models.ForeignKey(default=374, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forumpost'),
        ),
    ]
