# Generated by Django 4.2.17 on 2025-01-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_postcomment_forum_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='forum_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forumpost'),
        ),
    ]
